server:
  port: 8111
spring:  application:    name: gatewayservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-3-235-74-191.compute-1.amazonaws.com:8762/eureka

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
    connection-request-timeout-millis: 10000
  routes:    
    eureka:
      path: /eureka/**
      url: http://ec2-3-235-74-191.compute-1.amazonaws.com:8762/
    data:
      path: /data/**
      service-id: dataservice
    reports:
      path: /reports/**
      service-id: reportsservice